# Builds the self-contained speech engine into engine-dist\speechmatics_engine\.
#
# Run this whenever speechmatics_engine.py or requirements.txt changes, then
# build the app as usual. InterviewCopilot.csproj copies the result to engine\
# beside the app, and MainWindow prefers it over a system Python.
#
# The build deliberately uses a throwaway virtual environment. Building against
# the machine's global site-packages pulled unrelated libraries into the bundle
# and failed outright on a half-installed matplotlib.
#
#   powershell -ExecutionPolicy Bypass -File tools\build-engine.ps1

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

$venv = Join-Path $root "build\engine-venv"
$python = Join-Path $venv "Scripts\python.exe"

if (-not (Test-Path $python)) {
    Write-Host "Creating build virtual environment..."
    py -3 -m venv $venv
}

Write-Host "Installing engine dependencies..."
& $python -m pip install --quiet --upgrade pip
& $python -m pip install --quiet -r requirements.txt pyinstaller

# ── Stamp the source this engine was built from ──────────────────────────────
#
# "Which engine is this user running?" had no answer. The Mac app shipped a
# 1,074-line fork of this file for months while every build succeeded, and
# nothing anywhere would have caught it - not the build, not a test, not a
# support log. A binary that cannot say where it came from is one nobody can
# check.
#
# So the commit, the working-tree state and a hash of the source go into the
# bundle at build time, and the engine prints them on startup. The hash matters
# as much as the commit: a commit id says which revision was checked out, and
# the file hash says whether what was compiled is actually that revision.
$commit = (git rev-parse --short HEAD 2>$null)
if (-not $commit) { $commit = "nogit" }
$dirty = (git status --porcelain -- speechmatics_engine.py 2>$null)
if ($dirty) { $commit = "$commit+dirty" }

$srcPath = Join-Path $root "speechmatics_engine.py"
$srcHash = (Get-FileHash $srcPath -Algorithm SHA256).Hash.Substring(0, 12).ToLower()
$builtAt = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

# Stamped through a PyInstaller runtime hook rather than by editing the engine
# source, because that source is SHARED with the Mac app byte for byte and the
# hash is only worth anything if both platforms compute it over the same bytes.
#
# The first version of this did edit speechmatics_engine.py, adding a banner to
# it. That would have made the two platforms' hashes differ for identical
# logic — the provenance check reporting a divergence it had caused itself,
# which is worse than not having it. The Mac session spotted it and had already
# used a runtime hook for exactly this reason.
#
# A runtime hook runs before the main script, so the line still prints before
# anything in the engine can fail.
$hookDir = Join-Path $root "build\pyinstaller"
New-Item -ItemType Directory -Force $hookDir | Out-Null
$hook = Join-Path $hookDir "rthook_engine_build.py"

Write-Host "Stamping build: $commit / $srcHash"
@"
# Generated by tools/build-engine.ps1. Not committed, not part of the engine.
print(">>> ENGINE BUILD: $commit src:$srcHash built:$builtAt", flush=True)
"@ | Set-Content -Path $hook -Encoding utf8

Write-Host "Building engine..."
# pyaudiowpatch is imported inside a try/except, which PyInstaller's static
# analysis walked straight past, so the frozen engine silently fell back to
# stock pyaudio and lost WASAPI loopback. Without it, system audio needs a
# VB-Cable install, so collect it explicitly.
& $python -m PyInstaller --noconfirm --onedir `
    --collect-all pyaudiowpatch `
    --runtime-hook $hook `
    --name speechmatics_engine `
    --distpath (Join-Path $root "engine-dist") `
    --workpath (Join-Path $root "build\pyinstaller") `
    --specpath (Join-Path $root "build\pyinstaller") `
    (Join-Path $root "speechmatics_engine.py")

$exe = Join-Path $root "engine-dist\speechmatics_engine\speechmatics_engine.exe"
if (-not (Test-Path $exe)) { throw "Engine build produced no executable." }

# --collect-all drags in wheel source files and .dist-info metadata that the
# engine never reads. Harmless where it lands loose beside an exe, less so once
# it is inside a signed package: five packages ship identically named
# METADATA and RECORD files, and duplicate-name collisions inside a signed
# payload are a well-known way to fail packaging for a reason that reads as
# nothing to do with the cause.
#
# Found on the Mac side by building rather than by reading - Xcode tried to
# compile websockets/speedups.c and failed on a missing Python.h. MSBuild does
# not, but the MSIX payload is signed, so the metadata half applies here.
$dist = Split-Path $exe
$stripped = 0
foreach ($pattern in @("*.c", "*.h", "*.pyx", "*.pyi")) {
    Get-ChildItem $dist -Recurse -Filter $pattern -File -ErrorAction SilentlyContinue |
        ForEach-Object { Remove-Item $_.FullName -Force -ErrorAction SilentlyContinue; $stripped++ }
}
Get-ChildItem $dist -Recurse -Directory -Filter "*.dist-info" -ErrorAction SilentlyContinue |
    ForEach-Object { Remove-Item $_.FullName -Recurse -Force -ErrorAction SilentlyContinue; $stripped++ }
Write-Host "Stripped $stripped build-only files from the bundle."

$size = (Get-ChildItem (Split-Path $exe) -Recurse | Measure-Object -Property Length -Sum).Sum / 1MB
Write-Host ("Engine built: {0} ({1:N1} MB)" -f $exe, $size)
